name: ricky_morty
description: "A Flutter app that fetches data from the Rick and Morty API."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  http: ^1.2.1
  shimmer: ^3.0.0
  equatable: ^2.0.5
  graphql_flutter: ^5.1.2
  google_fonts: ^6.2.1
  win32: ^5.10.0
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.2

  get_it: ^8.0.3
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/all-cast-bg.png
    - assets/icons/
